version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mybookdb
